name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run Pytest tests
      run: pytest test_ftp_csv.py

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gui-ftp-csv:latest .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/gui-ftp-csv:latest

    - name: Add Username and Password (Run FTP server)
      run: |
        docker run -d --name ftp-csv-validator -p 21:21 -p 30000-30009:30000-30009 \
          -e FTP_USER_NAME=wla -e FTP_USER_PASS=wla123 stilliard/pure-ftpd:hardened
